'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class entity_scheduler

    '''<summary>
    '''panMasterRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panMasterRecord As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgMaster As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MasterRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MasterRecord As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Persons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Persons As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panPersonScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panPersonScope As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmdAppendJ02IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAppendJ02IDs As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdReplaceJ02IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdReplaceJ02IDs As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''j02ID_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j02ID_Add As Global.UI.person

    '''<summary>
    '''j11ID_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j11ID_Add As Global.UI.datacombo

    '''<summary>
    '''j07ID_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j07ID_Add As Global.UI.datacombo

    '''<summary>
    '''chkSetting_P48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSetting_P48 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSetting_O22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSetting_O22 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSetting_P56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSetting_P56 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''entity_scheduler_daystarttime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents entity_scheduler_daystarttime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''entity_scheduler_dayendtime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents entity_scheduler_dayendtime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''entity_scheduler_multidays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents entity_scheduler_multidays As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdExportICalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdExportICalendar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''scheduler1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scheduler1 As Global.Telerik.Web.UI.RadScheduler

    '''<summary>
    '''cmdHardRefreshOnBehind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdHardRefreshOnBehind As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hidJ02IDs_All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidJ02IDs_All As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidJ02IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidJ02IDs As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidJ07IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidJ07IDs As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidJ11IDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidJ11IDs As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidCurResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCurResource As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidCurTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCurTime As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMasterPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMasterPrefix As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMasterPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMasterPID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHardRefreshFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHardRefreshFlag As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHardRefreshPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHardRefreshPID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.Site
        Get
            Return CType(MyBase.Master, UI.Site)
        End Get
    End Property
End Class
