'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class entity_framework_p31summary

    '''<summary>
    '''period1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents period1 As Global.UI.periodcombo

    '''<summary>
    '''rpWaiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpWaiting As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''panApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panApproved As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rpApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpApproved As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''hidIsApprovingPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidIsApprovingPerson As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidIsInvoicingPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidIsInvoicingPerson As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMasterPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMasterPrefix As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMasterPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMasterPID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.SubForm
        Get
            Return CType(MyBase.Master, UI.SubForm)
        End Get
    End Property
End Class
