'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class j02_framework_detail

    '''<summary>
    '''placeBinMenuCss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents placeBinMenuCss As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''panMenuContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panMenuContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu1 As Global.Telerik.Web.UI.RadMenu

    '''<summary>
    '''panAdminCommands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panAdminCommands As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEdit As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''cmdEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEdit As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''imgNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNew As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''cmdNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNew As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''imgCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCopy As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''cmdCopy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCopy As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''panCommandPivot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panCommandPivot As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panO23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panO23 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmdO23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdO23 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''panO22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panO22 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmdO22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdO22 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''cmdP48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdP48 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''topLink0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topLink0 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''topLink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topLink1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''topLink4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topLink4 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''topLink2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topLink2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''topLink6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topLink6 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''topLink3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topLink3 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''panSwitch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSwitch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmdNewWindow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNewWindow As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FullNameAsc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FullNameAsc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j02Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j02Code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJ07Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJ07Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJ18Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJ18Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJ17Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJ17Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j07Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j07Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j18Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j18Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j17Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j17Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j02Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j02Email As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblFond control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFond As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''c21Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents c21Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Mediums control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mediums As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panIntraPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panIntraPerson As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''panAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panAccount As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j03Login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j03Login As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJ04Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJ04Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j04Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j04Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AccountMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdLog As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''cmdAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAccount As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''boxJ05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxJ05 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxJ05Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxJ05Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdAddJ05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddJ05 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''panSlaves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSlaves As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rpSlaves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpSlaves As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''SlavesInLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SlavesInLine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panMasters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panMasters As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rpMasters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpMasters As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''boxFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxFF As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxFFTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxFFTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkFFShowFilledOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFFShowFilledOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ff1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ff1 As Global.UI.freefields_readonly

    '''<summary>
    '''panP30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panP30 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rpP30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpP30 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''boxO23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxO23 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxO23Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxO23Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''notepad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notepad1 As Global.UI.o23_list

    '''<summary>
    '''opgSubgrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opgSubgrid As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''bigsummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bigsummary1 As Global.UI.p31_bigsummary

    '''<summary>
    '''gridP31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridP31 As Global.UI.p31_subgrid

    '''<summary>
    '''gridP56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridP56 As Global.UI.p56_subgrid

    '''<summary>
    '''gridP91 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridP91 As Global.UI.p91_subgrid

    '''<summary>
    '''hiddatapid_subform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddatapid_subform As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHardRefreshFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHardRefreshFlag As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHardRefreshPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHardRefreshPID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hiddatapid_p31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddatapid_p31 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cmdRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.SubForm
        Get
            Return CType(MyBase.Master, UI.SubForm)
        End Get
    End Property
End Class
