'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class o23_subgrid

    '''<summary>
    '''lblHeaderO23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderO23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbxGroupBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxGroupBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdO23_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdO23_new As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cmdO23_clone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdO23_clone As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cmdFullScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdFullScreen As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cbxPaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxPaging As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hidDefaultSorting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDefaultSorting As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidCols control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidCols As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidFrom As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''gridO23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridO23 As Global.UI.datagrid
End Class
