'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class o23_record

    '''<summary>
    '''panX20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panX20 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''x18Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x18Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''opgX20ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents opgX20ID As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''cbxType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxType As Global.UI.datacombo

    '''<summary>
    '''cbx1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx1 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''rpX19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpX19 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblX23ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblX23ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x23ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x23ID As Global.UI.datacombo

    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''o23Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents o23Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOrdinary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrdinary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''o23Ordinary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents o23Ordinary As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''lblo23Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblo23Code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''o23Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents o23Code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdChangeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdChangeCode As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''o23ArabicCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents o23ArabicCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panX16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panX16 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rpX16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpX16 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''panColors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panColors As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''o23BackColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents o23BackColor As Global.Telerik.Web.UI.RadColorPicker

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''o23ForeColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents o23ForeColor As Global.Telerik.Web.UI.RadColorPicker

    '''<summary>
    '''panHtmlEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panHtmlEditor As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''o23HtmlContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents o23HtmlContent As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''lblOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOwner As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j02ID_Owner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j02ID_Owner As Global.UI.person

    '''<summary>
    '''hidX18ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidX18ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidX29ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidX29ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidGUID_x19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidGUID_x19 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''SharedCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SharedCalendar As Global.Telerik.Web.UI.RadCalendar

    '''<summary>
    '''hidx18CalendarFieldStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidx18CalendarFieldStart As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidx18CalendarFieldEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidx18CalendarFieldEnd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.ModalDataRecord
        Get
            Return CType(MyBase.Master, UI.ModalDataRecord)
        End Get
    End Property
End Class
