'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class p41_framework_detail

    '''<summary>
    '''panMenuContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panMenuContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu1 As Global.Telerik.Web.UI.RadMenu

    '''<summary>
    '''panSwitch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panSwitch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxCoreTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxCoreTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdChilds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdChilds As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''cmdFavourite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdFavourite As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''trParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trParent As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ParentProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParentProject As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Project control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Project As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgFlag_Project control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFlag_Project As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgDraft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgDraft As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panDraftCommands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panDraftCommands As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Client As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''clue_client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clue_client As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''imgFlag_Client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFlag_Client As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''trWorkflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trWorkflow As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblB02ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblB02ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''b02Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b02Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdWorkflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdWorkflow As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''trPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPlan As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PlanPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlanPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''aP48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aP48 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''trP51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trP51 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblX51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblX51 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p51Name_Billing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p51Name_Billing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''clue_p51id_billing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clue_p51id_billing As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblX51_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblX51_Message As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblP42Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblP42Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p42Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p42Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''clue_p42name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clue_p42name As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblJ18Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJ18Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''j18Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents j18Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''clue_j18name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clue_j18name As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''boxX18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxX18 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxX18Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxX18Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''x18_binding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x18_binding As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''labels1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labels1 As Global.UI.x18_readonly

    '''<summary>
    '''boxP40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP40 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxP40Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP40Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rpP40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpP40 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''boxP31Summary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP31Summary As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxP31SummaryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP31SummaryTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''p31summary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p31summary1 As Global.UI.entity_worksheet_summary

    '''<summary>
    '''boxP30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP30 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxP30Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxP30Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdEditP30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditP30 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''persons1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents persons1 As Global.UI.contactpersons

    '''<summary>
    '''boxFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxFF As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxFFTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxFFTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkFFShowFilledOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFFShowFilledOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ff1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ff1 As Global.UI.freefields_readonly

    '''<summary>
    '''boxRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxRoles As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxRolesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxRolesTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''roles_project control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents roles_project As Global.UI.entityrole_assign_inline

    '''<summary>
    '''boxBillingMemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxBillingMemo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''p41BillingMemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p41BillingMemo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''boxO23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxO23 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''boxO23Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxO23Title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''notepad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notepad1 As Global.UI.o23_list

    '''<summary>
    '''tabs1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabs1 As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''fraSubform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fraSubform As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLoading As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hidHardRefreshFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHardRefreshFlag As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidHardRefreshPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidHardRefreshPID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidIsBin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidIsBin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidIsCanApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidIsCanApprove As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidParentWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidParentWidth As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cmdRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefresh As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.SubForm
        Get
            Return CType(MyBase.Master, UI.SubForm)
        End Get
    End Property
End Class
