'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class p41_framework_detail_budget

    '''<summary>
    '''p45ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p45ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdP45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdP45 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''cmdBudgetP46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBudgetP46 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''cmdBudgetP49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBudgetP49 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''cmdP47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdP47 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''cmdNewP49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNewP49 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''cmdConvert2P31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdConvert2P31 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''gridBudget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridBudget As Global.UI.datagrid

    '''<summary>
    '''panP49Setting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panP49Setting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkP49GroupByP34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkP49GroupByP34 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkP49GroupByP32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkP49GroupByP32 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hidBudgetPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidBudgetPID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UI.Clue
        Get
            Return CType(MyBase.Master, UI.Clue)
        End Get
    End Property
End Class
