'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class x25_record_readonly

    '''<summary>
    '''trB02Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trB02Name As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''b02Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents b02Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCode As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''x25Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x25Code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trName As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''x25Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents x25Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rpFF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpFF As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rpX19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpX19 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''Timestamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Timestamp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hidX18ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidX18ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPID As Global.System.Web.UI.WebControls.HiddenField
End Class
